# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personProjectWizard.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_placeProjectWizard(object):
    def setupUi(self, placeProjectWizard):
        placeProjectWizard.setObjectName("placeProjectWizard")
        placeProjectWizard.resize(898, 702)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/creepy/user"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        placeProjectWizard.setWindowIcon(icon)
        placeProjectWizard.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        placeProjectWizard.setOptions(QtWidgets.QWizard.HelpButtonOnRight)
        self.personProjectWizardPage1 = QtWidgets.QWizardPage()
        self.personProjectWizardPage1.setObjectName("personProjectWizardPage1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.personProjectWizardPage1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.personProjectDescriptionValue = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.personProjectDescriptionValue.setPlainText("")
        self.personProjectDescriptionValue.setObjectName("personProjectDescriptionValue")
        self.gridLayout_3.addWidget(self.personProjectDescriptionValue, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        self.personProjectNameValue = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.personProjectNameValue.setObjectName("personProjectNameValue")
        self.gridLayout_3.addWidget(self.personProjectNameValue, 0, 1, 1, 1)
        self.personProjectNameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.personProjectNameLabel.setEnabled(True)
        self.personProjectNameLabel.setObjectName("personProjectNameLabel")
        self.gridLayout_3.addWidget(self.personProjectNameLabel, 0, 0, 1, 1)
        self.personProjectKeywordsValue = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.personProjectKeywordsValue.setObjectName("personProjectKeywordsValue")
        self.gridLayout_3.addWidget(self.personProjectKeywordsValue, 1, 1, 1, 1)
        self.personProjectDescriptionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personProjectDescriptionLabel.sizePolicy().hasHeightForWidth())
        self.personProjectDescriptionLabel.setSizePolicy(sizePolicy)
        self.personProjectDescriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.personProjectDescriptionLabel.setObjectName("personProjectDescriptionLabel")
        self.gridLayout_3.addWidget(self.personProjectDescriptionLabel, 2, 0, 1, 1)
        self.personProkectKeywordsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.personProkectKeywordsLabel.setObjectName("personProkectKeywordsLabel")
        self.gridLayout_3.addWidget(self.personProkectKeywordsLabel, 1, 0, 1, 1)
        placeProjectWizard.addPage(self.personProjectWizardPage1)
        self.personProjectWizardPage2 = QtWidgets.QWizardPage()
        self.personProjectWizardPage2.setObjectName("personProjectWizardPage2")
        self.gridLayout = QtWidgets.QGridLayout(self.personProjectWizardPage2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnAddTarget = QtWidgets.QPushButton(self.personProjectWizardPage2)
        self.btnAddTarget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnAddTarget.setStyleSheet("")
        self.btnAddTarget.setObjectName("btnAddTarget")
        self.horizontalLayout.addWidget(self.btnAddTarget)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 3, 1, 1)
        self.personProjectSelectedTargetsTable = QtWidgets.QTableView(self.personProjectWizardPage2)
        self.personProjectSelectedTargetsTable.setDragEnabled(False)
        self.personProjectSelectedTargetsTable.setDragDropOverwriteMode(True)
        self.personProjectSelectedTargetsTable.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.personProjectSelectedTargetsTable.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.personProjectSelectedTargetsTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.personProjectSelectedTargetsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.personProjectSelectedTargetsTable.setSortingEnabled(True)
        self.personProjectSelectedTargetsTable.setObjectName("personProjectSelectedTargetsTable")
        self.personProjectSelectedTargetsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.personProjectSelectedTargetsTable.horizontalHeader().setStretchLastSection(True)
        self.personProjectSelectedTargetsTable.verticalHeader().setVisible(False)
        self.personProjectSelectedTargetsTable.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.personProjectSelectedTargetsTable, 8, 2, 1, 2)
        self.personProjectTargetSeperatorLine = QtWidgets.QFrame(self.personProjectWizardPage2)
        self.personProjectTargetSeperatorLine.setLineWidth(4)
        self.personProjectTargetSeperatorLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.personProjectTargetSeperatorLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.personProjectTargetSeperatorLine.setObjectName("personProjectTargetSeperatorLine")
        self.gridLayout.addWidget(self.personProjectTargetSeperatorLine, 6, 1, 1, 3)
        self.personProjectSearchResultsTable = QtWidgets.QTableView(self.personProjectWizardPage2)
        self.personProjectSearchResultsTable.setDragEnabled(True)
        self.personProjectSearchResultsTable.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.personProjectSearchResultsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.personProjectSearchResultsTable.setSortingEnabled(True)
        self.personProjectSearchResultsTable.setObjectName("personProjectSearchResultsTable")
        self.personProjectSearchResultsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.personProjectSearchResultsTable.horizontalHeader().setStretchLastSection(True)
        self.personProjectSearchResultsTable.verticalHeader().setVisible(False)
        self.personProjectSearchResultsTable.verticalHeader().setCascadingSectionResizes(True)
        self.personProjectSearchResultsTable.verticalHeader().setMinimumSectionSize(19)
        self.personProjectSearchResultsTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.personProjectSearchResultsTable, 4, 2, 1, 2)
        self.personProjectSearchForLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSearchForLabel.setObjectName("personProjectSearchForLabel")
        self.gridLayout.addWidget(self.personProjectSearchForLabel, 0, 0, 1, 2)
        self.personProjectSearchResultsLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSearchResultsLabel.setObjectName("personProjectSearchResultsLabel")
        self.gridLayout.addWidget(self.personProjectSearchResultsLabel, 4, 0, 1, 1)
        self.personProjectSelectedTargetsLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSelectedTargetsLabel.setObjectName("personProjectSelectedTargetsLabel")
        self.gridLayout.addWidget(self.personProjectSelectedTargetsLabel, 8, 0, 1, 1)
        self.personProjectSearchInLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        self.personProjectSearchInLabel.setObjectName("personProjectSearchInLabel")
        self.gridLayout.addWidget(self.personProjectSearchInLabel, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.personProjectSearchForDetailsLabel = QtWidgets.QLabel(self.personProjectWizardPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personProjectSearchForDetailsLabel.sizePolicy().hasHeightForWidth())
        self.personProjectSearchForDetailsLabel.setSizePolicy(sizePolicy)
        self.personProjectSearchForDetailsLabel.setObjectName("personProjectSearchForDetailsLabel")
        self.gridLayout.addWidget(self.personProjectSearchForDetailsLabel, 0, 3, 1, 1)
        self.personProjectAvailablePluginsScrollArea = QtWidgets.QScrollArea(self.personProjectWizardPage2)
        self.personProjectAvailablePluginsScrollArea.setWidgetResizable(True)
        self.personProjectAvailablePluginsScrollArea.setObjectName("personProjectAvailablePluginsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 99, 99))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.personProjectAvailablePluginsListView = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.personProjectAvailablePluginsListView.setObjectName("personProjectAvailablePluginsListView")
        self.verticalLayout.addWidget(self.personProjectAvailablePluginsListView)
        self.personProjectAvailablePluginsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.personProjectAvailablePluginsScrollArea, 1, 2, 1, 2)
        self.personProjectSearchForValue = QtWidgets.QLineEdit(self.personProjectWizardPage2)
        self.personProjectSearchForValue.setObjectName("personProjectSearchForValue")
        self.gridLayout.addWidget(self.personProjectSearchForValue, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.personProjectSearchButton = QtWidgets.QPushButton(self.personProjectWizardPage2)
        self.personProjectSearchButton.setDefault(True)
        self.personProjectSearchButton.setObjectName("personProjectSearchButton")
        self.horizontalLayout_2.addWidget(self.personProjectSearchButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 9, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnRemoveTarget = QtWidgets.QPushButton(self.personProjectWizardPage2)
        self.btnRemoveTarget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRemoveTarget.setStyleSheet("")
        self.btnRemoveTarget.setObjectName("btnRemoveTarget")
        self.horizontalLayout_3.addWidget(self.btnRemoveTarget)
        self.gridLayout.addLayout(self.horizontalLayout_3, 9, 3, 1, 1)
        placeProjectWizard.addPage(self.personProjectWizardPage2)
        self.personProjectWizardPage3 = QtWidgets.QWizardPage()
        self.personProjectWizardPage3.setObjectName("personProjectWizardPage3")
        self.personProjectWizardSearchConfigPluginsList = QtWidgets.QListView(self.personProjectWizardPage3)
        self.personProjectWizardSearchConfigPluginsList.setGeometry(QtCore.QRect(0, 0, 256, 531))
        self.personProjectWizardSearchConfigPluginsList.setObjectName("personProjectWizardSearchConfigPluginsList")
        self.searchConfiguration = QtWidgets.QStackedWidget(self.personProjectWizardPage3)
        self.searchConfiguration.setGeometry(QtCore.QRect(260, 0, 591, 531))
        self.searchConfiguration.setObjectName("searchConfiguration")
        placeProjectWizard.addPage(self.personProjectWizardPage3)
        self.personProjectWizardPage4 = QtWidgets.QWizardPage()
        self.personProjectWizardPage4.setObjectName("personProjectWizardPage4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.personProjectWizardPage4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        placeProjectWizard.addPage(self.personProjectWizardPage4)

        self.retranslateUi(placeProjectWizard)
        QtCore.QMetaObject.connectSlotsByName(placeProjectWizard)

    def retranslateUi(self, placeProjectWizard):
        _translate = QtCore.QCoreApplication.translate
        placeProjectWizard.setWindowTitle(_translate("placeProjectWizard", "New Person Project"))
        self.personProjectWizardPage1.setTitle(_translate("placeProjectWizard", "Step 1 - Set Project Metadata"))
        self.personProjectWizardPage1.setSubTitle(_translate("placeProjectWizard", "Add project related information"))
        self.personProjectNameValue.setPlaceholderText(_translate("placeProjectWizard", "Add a name for your project"))
        self.personProjectNameLabel.setText(_translate("placeProjectWizard", "Project Name "))
        self.personProjectKeywordsValue.setPlaceholderText(_translate("placeProjectWizard", "Add comma seperated keywords for your project"))
        self.personProjectDescriptionLabel.setText(_translate("placeProjectWizard", "Description"))
        self.personProkectKeywordsLabel.setText(_translate("placeProjectWizard", "Keywords"))
        self.personProjectWizardPage2.setTitle(_translate("placeProjectWizard", "Step 2 - Set the target"))
        self.personProjectWizardPage2.setSubTitle(_translate("placeProjectWizard", "Search for the person you want to track using the available plugins and add it to the <font color=\"red\">selected targets</font> by drag and drop or by clicking \"Add To Targets\""))
        self.btnAddTarget.setText(_translate("placeProjectWizard", "Add To Targets"))
        self.personProjectSearchForLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search for</span></p></body></html>"))
        self.personProjectSearchResultsLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search Results </span></p></body></html>"))
        self.personProjectSelectedTargetsLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Selected Targets</span></p></body></html>"))
        self.personProjectSearchInLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search In</span></p></body></html>"))
        self.personProjectSearchForDetailsLabel.setText(_translate("placeProjectWizard", "Search by username, mail, full name, id"))
        self.personProjectSearchButton.setToolTip(_translate("placeProjectWizard", "Search for targets in the selected plugins"))
        self.personProjectSearchButton.setText(_translate("placeProjectWizard", "Search"))
        self.btnRemoveTarget.setText(_translate("placeProjectWizard", "Remove Selected"))
        self.personProjectWizardPage3.setTitle(_translate("placeProjectWizard", "Step 3 - Set Parameters"))
        self.personProjectWizardPage3.setSubTitle(_translate("placeProjectWizard", "Provide the necessary search parameters for the plugins you are using"))
        self.personProjectWizardPage4.setTitle(_translate("placeProjectWizard", "Step 4  - Finalize Project"))
        self.personProjectWizardPage4.setSubTitle(_translate("placeProjectWizard", "Click Finish to save the Project Configuration "))

import creepy_resources_rc
