# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'placeProjectWizard.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_placeProjectWizard(object):
    def setupUi(self, placeProjectWizard):
        placeProjectWizard.setObjectName("placeProjectWizard")
        placeProjectWizard.resize(898, 702)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/creepy/user"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        placeProjectWizard.setWindowIcon(icon)
        placeProjectWizard.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        placeProjectWizard.setOptions(QtWidgets.QWizard.HelpButtonOnRight)
        self.placeProjectWizardPage1 = QtWidgets.QWizardPage()
        self.placeProjectWizardPage1.setObjectName("placeProjectWizardPage1")
        self.gridLayoutWidget = QtWidgets.QWidget(self.placeProjectWizardPage1)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 591))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.placeProjectDescriptionValue = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.placeProjectDescriptionValue.setPlainText("")
        self.placeProjectDescriptionValue.setObjectName("placeProjectDescriptionValue")
        self.gridLayout_3.addWidget(self.placeProjectDescriptionValue, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 1)
        self.placeProjectNameValue = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.placeProjectNameValue.setObjectName("placeProjectNameValue")
        self.gridLayout_3.addWidget(self.placeProjectNameValue, 0, 1, 1, 1)
        self.placeProjectNameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.placeProjectNameLabel.setEnabled(True)
        self.placeProjectNameLabel.setObjectName("placeProjectNameLabel")
        self.gridLayout_3.addWidget(self.placeProjectNameLabel, 0, 0, 1, 1)
        self.placeProjectKeywordsValue = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.placeProjectKeywordsValue.setObjectName("placeProjectKeywordsValue")
        self.gridLayout_3.addWidget(self.placeProjectKeywordsValue, 1, 1, 1, 1)
        self.placeProjectDescriptionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeProjectDescriptionLabel.sizePolicy().hasHeightForWidth())
        self.placeProjectDescriptionLabel.setSizePolicy(sizePolicy)
        self.placeProjectDescriptionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.placeProjectDescriptionLabel.setObjectName("placeProjectDescriptionLabel")
        self.gridLayout_3.addWidget(self.placeProjectDescriptionLabel, 2, 0, 1, 1)
        self.personProkectKeywordsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.personProkectKeywordsLabel.setObjectName("personProkectKeywordsLabel")
        self.gridLayout_3.addWidget(self.personProkectKeywordsLabel, 1, 0, 1, 1)
        placeProjectWizard.addPage(self.placeProjectWizardPage1)
        self.placeProjectWizardPage2 = QtWidgets.QWizardPage()
        self.placeProjectWizardPage2.setObjectName("placeProjectWizardPage2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.placeProjectWizardPage2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 871, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.containerLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.containerLayout.setObjectName("containerLayout")
        self.titleLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setTextFormat(QtCore.Qt.RichText)
        self.titleLabel.setObjectName("titleLabel")
        self.containerLayout.addWidget(self.titleLabel)
        self.webView = QtWebKitWidgets.QWebView(self.verticalLayoutWidget)
        self.webView.setProperty("url", QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.containerLayout.addWidget(self.webView)
        self.searchAddressLayout = QtWidgets.QHBoxLayout()
        self.searchAddressLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.searchAddressLayout.setObjectName("searchAddressLayout")
        self.searchAddressLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.searchAddressLabel.setObjectName("searchAddressLabel")
        self.searchAddressLayout.addWidget(self.searchAddressLabel)
        self.searchAddressInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.searchAddressInput.setInputMask("")
        self.searchAddressInput.setObjectName("searchAddressInput")
        self.searchAddressLayout.addWidget(self.searchAddressInput)
        self.searchAddressButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.searchAddressButton.setObjectName("searchAddressButton")
        self.searchAddressLayout.addWidget(self.searchAddressButton)
        self.containerLayout.addLayout(self.searchAddressLayout)
        self.controlsContainerLayout = QtWidgets.QHBoxLayout()
        self.controlsContainerLayout.setObjectName("controlsContainerLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlsContainerLayout.addItem(spacerItem1)
        self.radiusLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusLabel.sizePolicy().hasHeightForWidth())
        self.radiusLabel.setSizePolicy(sizePolicy)
        self.radiusLabel.setTextFormat(QtCore.Qt.RichText)
        self.radiusLabel.setObjectName("radiusLabel")
        self.controlsContainerLayout.addWidget(self.radiusLabel)
        self.radiusSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusSpinBox.sizePolicy().hasHeightForWidth())
        self.radiusSpinBox.setSizePolicy(sizePolicy)
        self.radiusSpinBox.setMaximum(1000)
        self.radiusSpinBox.setObjectName("radiusSpinBox")
        self.controlsContainerLayout.addWidget(self.radiusSpinBox)
        self.radiusUnitComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radiusUnitComboBox.sizePolicy().hasHeightForWidth())
        self.radiusUnitComboBox.setSizePolicy(sizePolicy)
        self.radiusUnitComboBox.setObjectName("radiusUnitComboBox")
        self.controlsContainerLayout.addWidget(self.radiusUnitComboBox)
        self.containerLayout.addLayout(self.controlsContainerLayout)
        placeProjectWizard.addPage(self.placeProjectWizardPage2)
        self.placeProjectWizardPage3 = QtWidgets.QWizardPage()
        self.placeProjectWizardPage3.setObjectName("placeProjectWizardPage3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.placeProjectWizardPage3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 841, 601))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.containerLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.containerLayout_2.setObjectName("containerLayout_2")
        self.placeProjectSearchInLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.placeProjectSearchInLabel.setObjectName("placeProjectSearchInLabel")
        self.containerLayout_2.addWidget(self.placeProjectSearchInLabel)
        self.placeProjectAvailablePluginsListView = QtWidgets.QListView(self.verticalLayoutWidget_2)
        self.placeProjectAvailablePluginsListView.setObjectName("placeProjectAvailablePluginsListView")
        self.containerLayout_2.addWidget(self.placeProjectAvailablePluginsListView)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.containerLayout_2.addItem(spacerItem2)
        placeProjectWizard.addPage(self.placeProjectWizardPage3)
        self.placeProjectWizardPage4 = QtWidgets.QWizardPage()
        self.placeProjectWizardPage4.setObjectName("placeProjectWizardPage4")
        self.placeProjectWizardSearchConfigPluginsList = QtWidgets.QListView(self.placeProjectWizardPage4)
        self.placeProjectWizardSearchConfigPluginsList.setGeometry(QtCore.QRect(0, 0, 256, 531))
        self.placeProjectWizardSearchConfigPluginsList.setObjectName("placeProjectWizardSearchConfigPluginsList")
        self.searchConfiguration = QtWidgets.QStackedWidget(self.placeProjectWizardPage4)
        self.searchConfiguration.setGeometry(QtCore.QRect(260, 0, 591, 531))
        self.searchConfiguration.setObjectName("searchConfiguration")
        placeProjectWizard.addPage(self.placeProjectWizardPage4)
        self.placeProjectWizardPage5 = QtWidgets.QWizardPage()
        self.placeProjectWizardPage5.setObjectName("placeProjectWizardPage5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.placeProjectWizardPage5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        placeProjectWizard.addPage(self.placeProjectWizardPage5)

        self.retranslateUi(placeProjectWizard)
        QtCore.QMetaObject.connectSlotsByName(placeProjectWizard)

    def retranslateUi(self, placeProjectWizard):
        _translate = QtCore.QCoreApplication.translate
        placeProjectWizard.setWindowTitle(_translate("placeProjectWizard", "New Place Project"))
        self.placeProjectWizardPage1.setTitle(_translate("placeProjectWizard", "Step 1 - Set Project Metadata"))
        self.placeProjectWizardPage1.setSubTitle(_translate("placeProjectWizard", "Add project related information"))
        self.placeProjectNameValue.setPlaceholderText(_translate("placeProjectWizard", "Add a name for your project"))
        self.placeProjectNameLabel.setText(_translate("placeProjectWizard", "Project Name "))
        self.placeProjectKeywordsValue.setPlaceholderText(_translate("placeProjectWizard", "Add comma seperated keywords for your project"))
        self.placeProjectDescriptionLabel.setText(_translate("placeProjectWizard", "Description"))
        self.personProkectKeywordsLabel.setText(_translate("placeProjectWizard", "Keywords"))
        self.placeProjectWizardPage2.setTitle(_translate("placeProjectWizard", "Step 2 - Set the target"))
        self.placeProjectWizardPage2.setSubTitle(_translate("placeProjectWizard", "Select the Point Of Interest and the distance around which you want to get results"))
        self.titleLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-size:9pt;\">Drop a </span><span style=\" font-size:9pt; font-weight:600; color:#ff0000;\">pin</span><span style=\" font-size:9pt;\"> on the map for your point of interest</span></p></body></html>"))
        self.searchAddressLabel.setText(_translate("placeProjectWizard", "Address"))
        self.searchAddressButton.setText(_translate("placeProjectWizard", "Search"))
        self.radiusLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-size:9pt;\">Distance from the POI :</span></p></body></html>"))
        self.placeProjectSearchInLabel.setText(_translate("placeProjectWizard", "<html><head/><body><p><span style=\" font-weight:600;\">Search In</span></p></body></html>"))
        self.placeProjectWizardPage4.setTitle(_translate("placeProjectWizard", "Step 3 - Set Parameters"))
        self.placeProjectWizardPage4.setSubTitle(_translate("placeProjectWizard", "Provide the necessary search parameters for the plugins you are using"))
        self.placeProjectWizardPage5.setTitle(_translate("placeProjectWizard", "Step 4  - Finalize Project"))
        self.placeProjectWizardPage5.setSubTitle(_translate("placeProjectWizard", "Click Finish to save the Project Configuration "))

from PyQt5 import QtWebKitWidgets
import creepy_resources_rc
